### ISSUE TITLE
Exception thrown on undefined data values

### ISSUE THREAD

**Issue by UppaJung** [ventojs/vento#26]
Vento (via the JS enginge?) throws an exception if a value isn't defined.

Hence, if `a` is undefined and `b` is set to "`foo`", one would expect `a ?? b` or `a || b` to result in `foo`, but instead it results in an exception.

**Comment by UppaJung** [comment]
My workaround for problems like `title` being undefined has been to make sure everything that uses the template has an empty string assigned to `title`

```yaml
title:
```

**Comment by oscarotero** [comment]
Yes, this is how JavaScript works and I think there's no way to call an undefined variable without throwing an error.

If you don't care if a variable is defined or not, use `{{ it.varname }}` instead of `{{ varname }}`. The `it` global variable contains all defined variables.

**Comment by wrapperup** [comment]
As of #43, this issue is fixed. @UppaJung give it a try and let us know 👍
