### ISSUE TITLE
help me pls, why im unable to ascess props?

### ISSUE THREAD

**Issue by ArnavK-09** [ventojs/vento#39]
![image](https://github.com/oscarotero/vento/assets/69188140/595567b3-c225-4429-823d-67286fa5c0ad)

![image](https://github.com/oscarotero/vento/assets/69188140/7ff1e619-17d3-488b-9866-4e5f1d032016)

**Comment by oscarotero** [comment]
If the variable doesn't exist, `heading ?? "My section"` [will fail](https://vento.js.org/configuration/#usewith).
Change it to `it.heading ?? "My section"` (referencing the variable from `it` global object).

**Comment by ArnavK-09** [comment]
> If the variable doesn't exist, `heading ?? "My section"` [will fail](https://vento.js.org/configuration/#usewith).
> Change it to `it.heading ?? "My section"` (referencing the variable from `it` global object).


# https://vento.js.org/syntax/layout/#data

I followed this and here it is not used 🤔

**Comment by oscarotero** [comment]
Hmm. In your capture you're including `skill.vto` file but the condition is in `section.vto`.
Are you sure this is correct?

If so, do you have a repo that I can clone for debugging?

**Comment by ArnavK-09** [comment]
Ohhh man I'm stupid!
Sorry!

But, if I'll use ` it.heading ` it won't throw error in section component if no heading given...I'll try that

Soo sorry 😢
