### ISSUE TITLE
Bun support? 

### ISSUE THREAD

**Issue by mimiMonads** [ventojs/vento#40]
Hello, I'm adding templates to my SSR engine which works in Deno and Bun, and my question is, would you give support to Bun in the future if we're required?

**Comment by oscarotero** [comment]
Vento is published on NPM (https://www.npmjs.com/package/ventojs) so it should be compatible with Bun.

**Comment by mimiMonads** [comment]
Well I guess that it's up to Bun to follow the nodejs standards, thanks for your time.

**Comment by oscarotero** [comment]
What issues are you having with Bun?

**Comment by mimiMonads** [comment]
Everything solved! I was having some issues related with my lazy implementation and the way that bun implements promises (I just chain everything). Vento should be natively working in my next release, thanks

**Comment by oscarotero** [comment]
Great!
