### ISSUE TITLE
Object assignment

### ISSUE THREAD

**Issue by oscarotero** [ventojs/vento#49]
I just realized with the removal of `with` in #43 that now it's not possible to assign variables to an object like this:

```js
{{ import "filename.vto" { username } }}
```

It's needed to do:

```js
{{ import "filename.vto" { username: username } }}
```

@wrapperup do you think is possible to implement this? I can try but maybe it's easier for you because you have more experience creating the transformer.

**Comment by wrapperup** [comment]
Ah I see, I guess we need to rewrite those as well. Sure I can do it.
