### ISSUE TITLE
Feature request: Cloudflare Worker support

### ISSUE THREAD

**Issue by jvhellemond** [ventojs/vento#68]
Hi,
Are there any plans to make Vento compatible with Cloudflare Workers? I tried bundling the npm package (using esbuild), but ran into the dreaded `Dynamic require of "node:fs" is not supported` errors (et al.).

I know Vento is specifically a Deno project, but it would be awesome for my projects.

**Comment by oscarotero** [comment]
Vento has [an NPM distribution](https://www.npmjs.com/package/ventojs). Did you try it?

**Comment by jvhellemond** [comment]
Yes, but that results in errors like `Dynamic require of "node:fs" is not supported`. Cloudflare Workers is a bit like node, but not enough :|

**Comment by oscarotero** [comment]
Do you know in which package/file where this error occurs?
I don't see any `node:fs` in Vento code (npm version). Maybe it's caused by a dependency.

**Comment by jvhellemond** [comment]
Yup, the dependency is `@deno/shim-deno`. The Cloudflare worker environment has no access to the filesystem, so `node:fs` is not available.

**Comment by oscarotero** [comment]
If Cloudflare has no access to file system, you have to replace the default loader with other with support for Cloudflare API.
The default loader [is this](https://github.com/ventojs/vento/blob/main/src/loader.ts). You can do something like this:

```js
class CloudflareLoader {
  async load(file) {
    return {
      source: "File content here"
    }
  }

  resolve(from, file) {
    return "Resolved file";
  }
}


const env = vento({
  includes: new CloudflareLoader()
});

```

**Comment by jvhellemond** [comment]
Creating a Cloudflare workerd loader is the way to do this, so closing this issue ✌️

**Comment by jvhellemond** [comment]
FWIW: I finally got round to trying this. File loaders are no longer an issue for Cloudflare workers with Node compatibility (`node:fs` et al. are now shimmed/polyfilled), but the platform does not allow code generation from strings (`eval`, `new Function`) as used in `core/environment`. Without a workaround for that, no Vento on Cloudflare :/
