### ISSUE TITLE
Allow the trimming syntax in comments

### ISSUE THREAD

**Issue by valtlai** [ventojs/vento#70]
I would expect the following comments to trim white space before them:

```njk
/*
  Content-Security-Policy:
    {#- #} default-src 'none';
    {#- #} style-src 'self';
    {#- #} base-uri 'none';
```

So the result would be:

```
/*
  Content-Security-Policy: default-src 'none'; style-src 'self'; base-uri 'none';
```

The code works like this in Nunjucks. In Vento, the `-` character is part of the comment, so it doesn’t do anything, and a syntax like `{{-# #}}` is a parsing error.

Therefore, I propose that we add support for the `{{#-` start tag and the `-#}}` end tag (or `{{-#` and `#-}}`, respectively, if they’re better – personally I don’t think so).

**Comment by oscarotero** [comment]
that's a good idea.
I just implemented this and will be available in the next version of Vento.

**Comment by valtlai** [comment]
Thank you so much for the quick fix – and for the whole project: it’s so great to have modern, actively maintained templating engine.
