### ISSUE TITLE
Is ` - }}` allowed?

### ISSUE THREAD

**Issue by dogfuntom** [ventojs/vento#77]
A layout code with a space between the hyphen (minus) and the closing curly brackets results in an exception. For example:

```nunjucks
<ul>
  {{ for n of 12 - }}
  <li>{{ n }}</li>
  {{ /for }}
</ul>
``` 

I ask because [markup_fmt](https://github.com/g-plane/markup_fmt) for *dprint* “wants” such syntax by default. For example: <https://dprint.dev/playground/#code/DwVwNgBAfAsAUAbwRFq3owMwPYCcIB2E2mEAjAEwQC0AvrfMGAJapRKET3AD0LasRMh4589Rj3AooQA/plugin/markup_fmt> (switch file extension to `.vto` after opening).

**Comment by oscarotero** [comment]
If you want to trim the next content, it must be `-}}` without spaces. It's a way to distinguish between the trimming character and other operations like `{{ n-- }}`.
For example, you can decrement a variable and trim the space with `{{ n-- -}}`

**Comment by dogfuntom** [comment]
Fixed on the markup_fmt side: https://github.com/g-plane/markup_fmt/issues/66.
