### ISSUE TITLE
Loader resolves all paths from `includes` dir

### ISSUE THREAD

**Issue by jvhellemond** [ventojs/vento#80]
When configuring an environment with an `includes` option, the loader resolves template path (so not just includes or layouts) from this `includes` path. I would expect the loader to resolve template paths from the cwd and includes and layouts from the configured `includes` dir.

### Example

This runs fine:
```js
const env = vento();
env.run("foo.html");
```

But when I configure an includes dir, like so:
```js
const env = vento({includes: "bar/baz"});
env.run("foo.html");
```
I get the error `Uncaught NotFound: No such file or directory (os error 2): readfile 'bar/baz/foo.html'`. It appears that setting the `includes` option makes the loader resolve from this path for all files, not just `{{ include }}`s. Is that intentional?

**Comment by oscarotero** [comment]
If the file doesn't start with `./`, Vento resolves from the includes path. Maybe this should be explained in the docs.

This should work:
```js
const env = vento({includes: "bar/baz"});
env.run("./foo.html", {});
```

**Comment by jvhellemond** [comment]
Aha! Thanks for your quick replay. I was expecting the includes to path to only be applied to... well, includes :)

**Comment by oscarotero** [comment]
Yeah, that's confusing. The thing is includes use vento.run internally, so there's no difference 😅
