### ISSUE TITLE
Unexpected equality comparison difference between `==` and `===` 

### ISSUE THREAD

**Issue by uncenter** [ventojs/vento#83]
I'm struggling to understand why this equality check is different between the `==` and `===` in the following snippet:

```
<ul>
  {{ set items = ['A', 'B', 'C'] }}
  {{ for index, item of items }}
    <li>{{ item }}</li>
    {{ set isLast = index == (items.length - 1) }}
    {{ index }} == {{ items.length - 1 }} = {{ isLast }}
    {{# But using triple equals... #}}
    {{ set isLast = index === (items.length - 1) }}
    {{ index }} === {{ items.length - 1 }} = {{ isLast }}
  {{ /for }}
</ul>
```

[🔗 Playground](https://livecodes.io/?x=code/N4IgLglmA2CmIC4QDVYDswHsAEAHaAhgJ4DmATpgK5oAmIANCDbAM4DGZEukmaiIDEAAtYBOkgA8AW1hgC2NkIJkWsgLwAdEAFUAKgDEAtAA4t2APQA+DWmmz5aAjM0gAbhFgB3XJjJgzbLxg6GAunhA0YEJqzO5ssIbhkUL02BBoUBAE0Ibs2bBqAIwAdAAMZlaCQmBS0ACCYGAq-IRoJC7oAYQsLC5agnIkLIgA2gC6jARskK6wAKI0UL78UsoA1pS4gqtkG1sIoK0klAQk8EizGJiCgRgh-BKU0NZo2NjAwNiqYGnBUizYNTYEYAcjqINSIIAQhDsCCAMIgsbYAC+KJsbw+2AAZr40rRYAAPVJQWBSbCYbG-MkAtEYt7YCTQCCWLGk8loiTmZkvBnvT7fNIsAAyBBYPyB6WYhMBQIAFOyWMU4G0othDNhCgBKVHo14MtkEmVo2X86n-ZXoEhqjWFXWAs0QEVin50-WY4AAYmwUMoP0oLHSJGwTS4cGwsAAjidoErisVsJ63XysYKnaLxQ6pUTZfLFZbVUJ1ZqdcmDZ9s8aUbnHX8lSrrUXbfagWznZmy1jzLiyLqbFynpYQCjGOKiHBEIcCG0Tmd+GwejcgvckMPRxwuGBJyAjrPziAAFYEVxijfcJd3DD8NcgMdwFgiWTDBDjdecbjP18gBcsAAKZFYWRr0YXAKHiHpfE-CZvwDLApAAZVkSA2mfYARxACApB8PxUPQsAiFwVhJzw1gwFQndp2OU593wwj2HfLdGFuYIr1XdDZhUCBeH4ABmABWAZMEwWNt3QAgACM4HEEBsmgQQphmfdbhYYT4FHOQwADedoEwVQ6DRIA)

The output of the above is:

```
A
0 == 2 = false 0 === 2 = false
B
1 == 2 = false 1 === 2 = false
C
2 == 2 = true 2 === 2 = false
```

As you can see on the last line for C, the double equals (`==`) compares `2` and `2` and evaluates to true, wheres the triple equals (`===`) compares the same `2` and `2` and evaluates to false.

**Comment by oscarotero** [comment]
fixed in v1.12.12

**Comment by uncenter** [comment]
Instead of `Object.entries(item).map(([key, value]) => [parseInt(key, 10), value])` you should just be able to do `item.map((value, index) => [index, value])`.

**Comment by oscarotero** [comment]
@uncenter You're absolutely right. I can't belive I missed that 🤦
