### ISSUE TITLE
exec plugin

### ISSUE THREAD

**Issue by boehs** [ventojs/vento#86]
Hi, another odd request, sorry 😅. I have the following code:

```njk
{{for name,content of metaTags }}
    <meta name="{{name}}" content="{{content |> escape}}">
{{ /for }}
```

where metaTags is defined like

```json
{
    "viewport": "width=device-width,initial-scale=1",
    "theme-color": "{{color}}",
    "author": "{{config.author.name}}",
    "generator": "Eleventy"
}
```

Looking at the plugins, it would seem as if this could easily be another small plugin? something like `{{ exec "{{ blah blah }}" }}`

I'm trying to figure out the plugin development process for this

**Comment by boehs** [comment]
I'm starting to think this will be problematic. As I understand it, vento runs in two stages

1. Template built into javascript
2. Template executed with a given context

If you have code like

js```
{{for name,content of metaTags }}
    <meta name="{{name}}" content="{{content |> escape}}">
{{ /for }}
```

You don't know what content is until you're in the execution stage. Because you don't know what content is until you're executing, you don't know how to compile whatever the value of content may be. If you want to do that compilation during execution, you would need to embed all of vento inside the vento output

**Comment by oscarotero** [comment]
Yes, that's true.
Vento compiles your template:
```html
{{for name,content of metaTags }}
    <meta name="{{name}}" content="{{content |> escape}}">
{{ /for }}
```

to something like this:

```js
for (let [name, content] of __env.utils.toIterator(metaTags)) {
  __exports.content += `    <meta name="`;
  __exports.content += name;
  __exports.content += `" content="`;
  __exports.content += __env.filters.escape(content);
  __exports.content += `">`;
}
```

Both `__env.utils.toIterator` and `__env.filters.escape` are executed at runtime and they are stored in the `__env` variable (the environment instance of Vento).

I don't understand the plugin `{{ exec "{{ blah blah }}" }}`. What is this suposed to do?

**Comment by oscarotero** [comment]
Ah, got it.

I guess this is possible but possibly slow because Vento has to compile and run every item in the loop. I'm not sure but I think Eleventy has an option to compute these values automatically.

**Comment by boehs** [comment]
Yeah, there *should* be (practically, 11ty's implementation is also... flawed). There are workarounds, though the question still stands on if there is any way Vento can provide something analogous to `eval('')` in javascript. The conclusion "we don't want to support this due to (complexity|no good way to implement|...)" is perfectly satisfactory if that's where you're at, I just wanted to raise the question

**Comment by oscarotero** [comment]
I think it could be a perfect use case for a filter. Something like

```html
{{for name,content of metaTags }}
    <meta name="{{name}}" content="{{content |> vento |> escape}}">
{{ /for }}
```

The `vento` filter could be implemented as this:

```js
env.filters.vento = async function (code, data = {}) {
  return await env.runString(code, data).content;
};
```

For performance, we can generate a fake path hashing the code, if the same code is executed twice, it's only compiled the first time:

```js
env.filters.vento = async function (code, data = {}) {
  const file = `memory:${hash(code).vto`; // hash() function to be implemented
  return await env.runString(code, data, file).content;
};
```

**Comment by boehs** [comment]
Ah brilliant! This is what I wanted!

```ts
async function hash(message, algo = "SHA-1") {
  return Array.from(
    new Uint8Array(
      await crypto.subtle.digest(algo, new TextEncoder().encode(message)),
    ),
    (byte) => byte.toString(16).padStart(2, "0"),
  ).join("");
}

eleventyConfig.addPlugin(VentoPlugin, {
  plugins: [
    (env) => {
      env.filters.exec = async function (code) {
        const file = `memory:${await hash(code)}.vto`;
        let res = (await env.runString(code, this.data, file))
            .content;
        return res;
      };
    },
  ],
});
```

just a couple small changes (`this.data` instead of the data arg, await content properly, hash impl provided)
